services:
  - type: web
    name: convertnest
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start_render.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
